### ISSUE TITLE
halp!!

### ISSUE THREAD

**Issue by Creyni** [ajmeese7/spambot#18]
Hi im a complete novice at setting up bots and things so hoping somone can give me a step by step instruction manual on getting this to run please.

also is it possible to have this run on more than 1 server at a time?

**Comment by RealAwesomeness** [comment]
Try reading the readme first - there's a manual there. You cannot run it on more than one server at a time.
________________________________

**Comment by Creyni** [comment]
yeah i tried following the read me but my PC rejects the cd spambot command. im fairly sure its due to my inexperience though.

hmm ok was hopeful for more than one server. do you know of any bots that can spam in more than one server. I am trying to use it to spawn things when using bots like pokecord and waifubot.

**Comment by ajmeese7** [comment]
If you couldn't change directory into the spambot folder that means you didn't open the command prompt in the right location. Try reading this step more carefully: 
```In the folder from where you ran the git command, run 'cd spambot' and then run 'npm install'```

Also, @RealAwesomeness I just successfully ran it on two servers at a time on my PC. I don't think there is a limit on how many you can run it on. If you are still having issues feel free to reopen this, but I suspect the issue is you navigated to the wrong directory in your terminal.

**Comment by Creyni** [comment]
Hi there @ajmeese7

so i got it to work finally so yay!! for me lol

however i have some questions.

is there a list of commands? or is it just the /spam to start it.

are certain things editable about bot? I would like to remvoe the auto prune and perhaps speed the bot up very slightly but i dont have the first clue who i would do these
