### ISSUE TITLE
Bot won't send messages

### ISSUE THREAD

**Issue by Priyank77** [ajmeese7/spambot#62]
Hey man, first of all, thank you for making this selfbot! That being said, I want to say I followed the steps correctly because when I launch the js file with "Node bot.js" on the Node js cmp, the bot comes online. However, whenever I type "/spam", nothing happens. I tried debugging the bot.js file by loading the file through Node.js and it says that "Identifier Client has already been declared." I'm not entirely sure what to do.

**Comment by ajmeese7** [comment]
You're welcome!

Did you set the bot to listen for the command from your user account? If the bot is running then that's the main reason I can think of for why it doesn't respond to your command.

Did you modify the file at all to perhaps declare `Client` more than once?

**Comment by Priyank77** [comment]
Hey man thank you for the reply. I actually put in an actual bot token instead of a user token in the config so that's why it didn't work. 

It runs well except for when it stops and produces this error:

Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:220:20)

I have a stable internet connection so I'm not sure how to deal with this. Any ideas?

**Comment by ajmeese7** [comment]
It is possible that Discord has since changed their software to be better at detecting self bots and prevent this from working, I haven't had a need to use this software in a while so I am unsure at the moment. This response is typed from my phone, so I apologize in advance if the formatting looks strange.

I have several questions that may help me to better solve this problem:

1. How long after running the code do you begin to experience that error? 
2. Is the error fatal, meaning does it kill the process?
3. What do you have the time parameters set to?
4. Have you changed the random message to anything other than a set string?
5. Are there any other configuration changes that you have made, other than what I have asked about above?

**Comment by Priyank77** [comment]
1. It happens at random, but always at least after an hour or so
2. Yes, it does kill the process. It prints a lot of other things as well but I felt like it might be overwhelming to paste those here
3. I haven't set the time parameters
4. I only changed the message the string sends, keeping your format with the count
5. I have not

**Comment by ajmeese7** [comment]
My recommendation is to modify the bot to reconnect if it catches an `ECONNRESET` error, since it is likely a result of the server closing the connection as explained [here](https://github.com/discordjs/discord.js/issues/2227#issuecomment-355289315). Unfortunately that is all the best suggestion I can offer at the moment, but it should get the job done.

Please let me know if there's anything I can do to help!

**Comment by ajmeese7** [comment]
I'm going to close this for now due to inactivity, please reach out if there is anything else that you need help with!
