### ISSUE TITLE
discord.js version

### ISSUE THREAD

**Issue by natedawg92** [ajmeese7/spambot#68]
Hey, Excellent bot, and great template to be able to add further development. 

I did wonder though is there a particular reason why the bot requires Discord.js V11, I can see that it uses a forked version hosted on your account and can imagine that there have been some modifications (hands up, i haven't actually compared the copies in any detail though), One of the improvements i would like to take advantage of between 11 and 12 is the message collectors. which don't function quite as expected in v11.

**Comment by natedawg92** [comment]
you can probably just close this straight away, done a comparison of the 11.6.4 and 12.5.3 versions of discord.js and your forked version and there seems to be no differences actually

**Comment by ajmeese7** [comment]
@natedawg92 because Discord.js v12 has no support for selfbots, the feature is removed entirely and you will not be able to get any functionality out of it. My fork of v11 was updated to fix some bugs introduced by new Discord functionality that the folks at Discord.js opted to not patch since they are now opposed to the use of selfbots because they violate the Discord Terms of Service

**Comment by natedawg92** [comment]
Ah, fair enough might raise a PR or two to pull in some of the fixes from V12. Thanks for your response.

**Comment by ajmeese7** [comment]
Be my guest :) closing this out now
